# Generated by Django 5.2.9 on 2025-12-23 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('DEPOSIT', '정기예금'), ('SAVING', '적금')], max_length=10)),
                ('fin_prdt_cd', models.CharField(max_length=100, unique=True)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('fin_prdt_nm', models.CharField(max_length=100)),
                ('join_way', models.TextField(null=True)),
                ('mtrt_int', models.TextField(null=True)),
                ('spcl_cnd', models.TextField(null=True)),
                ('join_deny', models.IntegerField(null=True)),
                ('join_member', models.TextField(null=True)),
                ('etc_note', models.TextField(null=True)),
                ('rsrv_type_nm', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.CharField(max_length=100)),
                ('intr_rate_type_nm', models.CharField(max_length=100)),
                ('save_trm', models.IntegerField()),
                ('intr_rate', models.FloatField(null=True)),
                ('intr_rate2', models.FloatField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.financialproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_intr_rate', models.FloatField(help_text='가입 당시 기본 금리')),
                ('init_intr_rate2', models.FloatField(help_text='가입 당시 우대 금리')),
                ('init_save_trm', models.IntegerField(help_text='가입 당시 저축 기간(월)')),
                ('init_intr_rate_type_nm', models.CharField(help_text='가입 당시 금리 유형(단리/복리)', max_length=100)),
                ('amount', models.BigIntegerField(default=0)),
                ('subscribed_at', models.DateField(auto_now_add=True)),
                ('expired_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='products.productoption')),
            ],
        ),
    ]
