# Generated by Django 5.2.9 on 2025-12-21 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mydata_linked', models.BooleanField(default=False)),
                ('linked_org_count', models.IntegerField(default=0)),
                ('balance_amt', models.BigIntegerField(default=0, help_text='현재 잔액 합계')),
                ('withdrawable_amt', models.BigIntegerField(default=0, help_text='출금 가능 금액')),
                ('last_offered_rate', models.FloatField(default=0.0, help_text='현재 보유 상품 중 최고 금리')),
                ('monthly_paid_amt', models.IntegerField(default=0, help_text='월 평균 저축 금액')),
                ('invest_eval_amt', models.BigIntegerField(default=0, help_text='투자 자산 평가 금액')),
                ('invest_purchase_amt', models.BigIntegerField(default=0, help_text='투자 원금 합계')),
                ('annual_income_amt', models.BigIntegerField(default=0)),
                ('risk_tolerance', models.IntegerField(choices=[(0, '안정'), (1, '중립'), (2, '공격')], default=0)),
                ('cluster_label', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
