# Generated by Django 5.2.9 on 2025-12-21 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='depositoptions',
            unique_together={('product', 'save_trm', 'intr_rate_type_nm')},
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'deposit_option')},
        ),
    ]
