# Generated by Django 5.2.9 on 2025-12-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_financialprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialprofile',
            name='saving_purpose',
            field=models.CharField(choices=[('MOKDON', '목돈 마련'), ('EMERGENCY', '비상금'), ('RETIRE', '노후 준비')], default='MOKDON', max_length=20),
        ),
    ]
