# Generated by Django 5.2.9 on 2025-12-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_recommendationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
