# Generated by Django 5.2.9 on 2025-12-24 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productoption_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoption',
            name='embedding',
        ),
    ]
