# Generated by Django 5.2.9 on 2025-12-21 14:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('is_mydata_agreed', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mydata_linked', models.BooleanField(default=False)),
                ('linked_org_count', models.IntegerField(default=0)),
                ('balance_amt', models.BigIntegerField(default=0, help_text='현재 잔액 합계')),
                ('withdrawable_amt', models.BigIntegerField(default=0, help_text='출금 가능 금액')),
                ('last_offered_rate', models.FloatField(default=0.0, help_text='현재 보유 상품 중 최고 금리')),
                ('monthly_paid_amt', models.IntegerField(default=0, help_text='월 평균 저축 금액')),
                ('invest_eval_amt', models.BigIntegerField(default=0, help_text='투자 자산 평가 금액')),
                ('invest_purchase_amt', models.BigIntegerField(default=0, help_text='투자 원금 합계')),
                ('annual_income_amt', models.BigIntegerField(default=0)),
                ('cluster_label', models.IntegerField(blank=True, null=True)),
                ('saving_purpose', models.CharField(choices=[('MOKDON', '목돈 마련'), ('EMERGENCY', '비상금'), ('RETIRE', '노후 준비')], default='MOKDON', max_length=20)),
                ('expense_growth_rate', models.FloatField(default=1.0, help_text='전월 대비 지출 변동률')),
                ('expense_to_income_ratio', models.FloatField(default=0.0, help_text='소득 대비 지출 비율')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
