# Generated by Django 5.2.9 on 2025-12-18 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amounts', models.BigIntegerField(default=0)),
                ('subscribed_at', models.DateField(auto_now_add=True)),
                ('expired_at', models.DateField(blank=True, null=True)),
                ('deposit_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='products.depositoptions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'deposit_option')},
            },
        ),
    ]
