# Generated by Django 5.2.9 on 2025-12-25 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_financialprofile_cluster_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_mydata_agreed',
        ),
    ]
