# Generated by Django 5.2.9 on 2025-12-25 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_is_mydata_agreed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financialprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
